---
- name: packages install
  yum: name={{item}} state=present
  with_items:
    - openssh-server
    - ntp
    - zsh
    - git-svn
    - ansible
    - tmux

- name: enable services
  service: name={{item}} state=started enabled=yes
  with_items:
    - ssh

#- name: ntp step-tickers settings
#  template: src=etc_ntp_step-tickers.j2 dest=/etc/ntp/step-tickers owner=root group=root mode=0644
#  notify:
#    - ntpd restart
#
#- name: ntp.conf settings
#  template: src=ntp.conf.j2 dest=/etc/ntp.conf owner=root group=root mode=0644
#    - ntpd restart
#
#- name: /etc/sysconfig/ntpd settings
#  template: src=etc_sysconfig_ntpd.j2 dest=/etc/sysconfig/ntpd owner=root group=root mode=0644
#    - ntpd restart
#
#- name: ntpd running check
#  command: service ntpd status
#  register: running_ntpd
#  failed_when: running_ntpd.rc not in [0,1,3]
#  changed_when: running_ntpd.rc != 0
#
#- name: run ntpdate
#  service: name=ntpdate state=started
#  when: running_ntpd.rc == 1
#
#- name: enable ntpdate service
#  service: name=ntpdate enabled=yes
#
#- name: enable services
#  service: name={{item}} state=started enabled=yes
#  with_items:
#    - ntpd
