---
- name: packages update
  apt: update_cache=yes

- name: packages install
  apt: name={{item}} state=present
  with_items:
    - openssh-server
    - ntp
    - zsh
    - git-svn
    - ansible
    - sshpass
    - tmux

- name: enable services
  service: name={{item}} state=started enabled=yes
  with_items:
    - ssh

